import { NextResponse } from "next/server";
import { Connection } from "@solana/web3.js";
import bs58 from "bs58";
import { z } from "zod";
import { db } from "@/lib/db";
import { COOKIE_RPC, MEMO_PROGRAM } from "@/lib/chain";

export const runtime = "nodejs";
const bodySchema=z.object({id:z.string().regex(/^[a-f0-9-]{8,36}$/),creator:z.string().min(32).max(44),title:z.string().min(3).max(80),tagline:z.string().max(160).default("Community quest"),clue:z.string().min(3).max(1000),hint:z.string().max(300).default(""),answerHash:z.string().regex(/^[a-f0-9]{64}$/),rewardCook:z.number().min(0).max(1_000_000).default(0),maxWinners:z.number().int().min(1).max(10_000).default(100),signature:z.string().min(64).max(100)});
function instructionMemo(ix:unknown){if(!ix||typeof ix!=="object")return null;const obj=ix as {programId?:{toBase58?:()=>string};parsed?:unknown;data?:string};if(obj.programId?.toBase58?.()!==MEMO_PROGRAM.toBase58())return null;if(typeof obj.parsed==="string")return obj.parsed;if(typeof obj.data==="string")return new TextDecoder().decode(bs58.decode(obj.data));return null}
async function verify(signature:string,wallet:string,expected:string){const tx=await new Connection(COOKIE_RPC,"confirmed").getParsedTransaction(signature,{commitment:"confirmed",maxSupportedTransactionVersion:0});if(!tx||tx.meta?.err)throw new Error("Transaction is not confirmed.");const signer=tx.transaction.message.accountKeys.some(k=>k.signer&&k.pubkey.toBase58()===wallet);if(!signer)throw new Error("Creator did not sign this transaction.");const memos=tx.transaction.message.instructions.map(instructionMemo);if(!memos.includes(expected))throw new Error("Campaign proof does not match the transaction.")}
export async function GET(){try{const result=await db().query("select id, creator_wallet as creator, title, tagline, clue, hint, answer_hash as \"answerHash\", reward_cook::float8 as \"rewardCook\", max_winners as \"maxWinners\", create_signature as signature, created_at as \"createdAt\" from quests where active order by created_at desc limit 100");return NextResponse.json({campaigns:result.rows})}catch{return NextResponse.json({campaigns:[]})}}
export async function POST(request:Request){try{const data=bodySchema.parse(await request.json());const memo=`cq:v1:create:${data.id}:${data.answerHash}:${data.title}`;await verify(data.signature,data.creator,memo);await db().query("insert into quests(id,creator_wallet,title,tagline,clue,hint,answer_hash,reward_cook,max_winners,create_signature) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) on conflict(id) do nothing",[data.id,data.creator,data.title,data.tagline,data.clue,data.hint,data.answerHash,data.rewardCook,data.maxWinners,data.signature]);return NextResponse.json({ok:true},{status:201})}catch(e){const message=e instanceof Error?e.message:"Invalid campaign.";return NextResponse.json({error:message},{status:400})}}
