"use client";
import { useState } from "react";
import { ExternalLink } from "lucide-react";
import type { Quest } from "@/lib/quests";
import { explorerTx } from "@/lib/chain";
import { useWallet } from "@/components/wallet-provider";
async function sha256(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,"0")).join("")}
const normalize=(value:string)=>value.trim().toLowerCase().replace(/[^a-z0-9]/g,"");
export function QuestFlow({quest}:{quest:Quest}){const{address,connect,submitMemo}=useWallet();const[answer,setAnswer]=useState("");const[salt,setSalt]=useState("");const[commit,setCommit]=useState("");const[step,setStep]=useState<"commit"|"reveal"|"claim"|"done">("commit");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[signature,setSignature]=useState("");async function act(){setBusy(true);setError("");try{if(!address){await connect();return}if(step==="commit"){if(!normalize(answer))throw new Error("Enter an answer before committing.");const nextSalt=crypto.randomUUID().replaceAll("-","");const hash=await sha256(`cookiequest:v1:${quest.id}:${normalize(answer)}:${nextSalt}`);const sig=await submitMemo(`cq:v1:commit:${quest.id}:${hash}`);setSalt(nextSalt);setCommit(hash);sessionStorage.setItem(`cq:${quest.id}:${address}`,JSON.stringify({answer,salt:nextSalt,commit:hash}));setSignature(sig);setStep("reveal")}else if(step==="reveal"){const sig=await submitMemo(`cq:v1:reveal:${quest.id}:${normalize(answer)}:${salt}`);setSignature(sig);setStep("claim")}else if(step==="claim"){const sig=await submitMemo(`cq:v1:claim:${quest.id}:${commit.slice(0,16)}`);setSignature(sig);setStep("done")}}catch(e){setError(e instanceof Error?e.message:"Transaction failed.")}finally{setBusy(false)}}const label=!address?"Connect Nightly":step==="commit"?"Commit answer":step==="reveal"?"Reveal answer":step==="claim"?"Record claim":"Claim recorded";return <><label htmlFor="answer">Normalized answer</label><input id="answer" placeholder="enter the word" value={answer} onChange={e=>setAnswer(e.target.value)} disabled={busy||step==="done"}/><button className="primary-button full" onClick={act} disabled={busy||step==="done"}>{busy?"Waiting for Nightly…":label}</button>{error&&<p className="error-note" role="alert">{error}</p>}{signature&&<a className="tx-link" href={explorerTx(signature)} target="_blank" rel="noreferrer">View confirmed transaction <ExternalLink size={14}/></a>}<p className="status-note">Each step is signed by your wallet and confirmed on Cookie Chain.</p></>}
